POST http://localhost:3001/api/tasks
Content-Type: application/json

{
    "name": "BCR Major",
    "category": "Lightcycler",
    "schedule": {
        "sunday": [8, 18],
        "monday": [],
        "tuesday": [],
        "wednesday": [8, 18],
        "thursday": [8, 18],
        "friday": [8, 18],
        "saturday": [8, 18]
    },
    "people": ["61392ff2af57cf99d391e3fe"],
    "time": 4
}

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "firstName": "Santa",
    "lastName": "Clause",
    "schedule": {
        "sunday": [8, "6:30"],
        "monday": [8, "6:30"],
        "tuesday": [8, "6:30"],
        "wednesday": [8, "6:30"]
    },
    "tasks": ["613936b2a26964e238951ede", "61392daeaf57cf99d391e3fc"],
    "daysOff": ["01-19-2024"]
}

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": {
        "first": "tom",
        "last": "cruise"
    },
    "schedule": {
        "sunday": {
            "timeIn": {
                "start":"8:00",
                "end":"6:30"
            }
        }
    },
    "tasks": ["613936b2a26964e238951ede", "61392daeaf57cf99d391e3fc"],
    "daysOff": []
}