POST http://localhost:3001/api/tasks
Content-Type: application/json

{
    "name": "BCR Major",
    "category": "Lightcycler",
    "schedule": {
        "sunday": [8, 18],
        "monday": [],
        "tuesday": [],
        "wednesday": [8, 18],
        "thursday": [8, 18],
        "friday": [8, 18],
        "saturday": [8, 18]
    },
    "people": ["61392ff2af57cf99d391e3fe"],
    "time": 4
}